### ISSUE TITLE
Sync-Settings: No Location Service

### ISSUE THREAD

**Issue by vizzale** [UziTech/sync-settings-folder-location#16]
Until a few days ago I used sync-settings to backup my settings and as a backup location I used a Gist. Yesterday I have installed sync-settings-folder-location and for the setting I followed the simple guide that is provided:

- Install Sync-Settings.
- Install Sync-Settings-folder-location.
- Go To the Sync-Settings settings page.
- Check Use Other Backup Location.
- Run command `sync-settings:create-backup` to create the backup location.
- Run command `sync-settings:backup` to backup your settings.

Despite this now every time I start Atom the program gives me this warning:

![Schermata 2020-04-22 alle 09 12 57](https://user-images.githubusercontent.com/37701762/80239464-93a0e900-8660-11ea-9aea-9175593aa7a9.png)

I can add that when I run the command `sync-settings:backup` the plugin seems to work, the files are present in the selected folder and gives me this warning:

![Schermata 2020-04-23 alle 20 04 27](https://user-images.githubusercontent.com/37701762/80239877-41ac9300-8661-11ea-8bb3-9b8511b58f1d.png)

But if I click on the "View backup" button nothing happens.

Thanks in advance for the help.

**Comment by vizzale** [comment]
Anyone have any suggestions?

**Comment by UziTech** [comment]
Sorry, I must've missed this in my notifications.

Can you provide the version of Atom and OS that you are using? And the path to the folder you are backing up to?

If you go to that folder on your computer can you see the files being backed up?

**Comment by vizzale** [comment]
No problem, it can happen :)

Below all the information you requested:
- Atom version: `1.45.0`
- macOS version: `10.12.6`
- backup folder chosen: `/Users/vizzale/Dropbox/Backup/Atom`

Finally yes, if I go inside the folder I can see the backup files.

**Comment by UziTech** [comment]
So Sync-Settings is using this package to backup the files even though it says it doesn't see that it is installed the first time it tries to check the backup.

Sync-settings is supposed to wait until all packages are activated before doing the initial check. I'm guessing it is a race condition between when the `sync-settings-folder-location` package registers the service and sync-settings checks for a change in the backup.

The only way to fix that would be to wait for any service to register before trying the initial check. That would be something that needs to be fixed in Sync-settings. (I will try to create a PR for that soon.)

For the "View Backup" button not working it might be a Mac issue. Sync-settings uses `shell.openExternal(folderLocation)` to open the folder. It works for me to execute `shell.openExternal('C:\\some path')` on windows to open the folder but my guess is `shell.openExternal('/Users/vizzale/Dropbox/Backup/Atom')` doesn't open the folder on a mac. I don't know how to make it work on a Mac and I don't have a Mac to test it on.

**Comment by UziTech** [comment]
I just released v4.3.3 of sync-settings. That should fix the Error notification on startup. We can reopen this if it didn't work.

**Comment by vizzale** [comment]
Hi @UziTech, I confirm that the problem that occurred no longer occurs.
However, two other problems occur, the first concerns general functioning, the second a particular case. The two problems are not related. I'll explain both in detail.


**General problem**

1) I make the first backup
2) I close Atom
3) I open Atom: obviously nothing appears because no changes have been made
4) I make a change to the settings
5) I close Atom
6) I open Atom: now the sync-settings plugin correctly warns me that changes have been made

![1](https://user-images.githubusercontent.com/37701762/80691303-59a46c80-8ad0-11ea-8aa6-7baca90a6044.png)

7) click on "View Diff" and the plugin shows me the differences:

![2](https://user-images.githubusercontent.com/37701762/80691349-6a54e280-8ad0-11ea-90b3-84cbb04df3d2.png)

but as you can see from the date this does not change 

8) Though I click on "Backup" the date doesn't change

I have done the procedure several times but the date shown is always wrong, i.e. the date of the first backup is always shown.


**Particular problem**

If I add an extra file to the backup for example:

![3](https://user-images.githubusercontent.com/37701762/80694521-ea7d4700-8ad4-11ea-852a-08bead89746f.png)

every time I open the program the system will always show me the previous screen even if nothing has changed:

![1](https://user-images.githubusercontent.com/37701762/80694555-f79a3600-8ad4-11ea-9d75-89ee6e1f9721.png)

**Comment by UziTech** [comment]
Could you open two new issues for these issues so we can keep track of them easier.

**Comment by vizzale** [comment]
Of course, in the meantime I did some tests.
The second problem may have been caused by my mistake, and occurred when I entered the full path of the file `toolbar.json`. In fact, if you enter in the "Extra Files" field simply the name of the file without the entire path, there is no problem.

**Comment by UziTech** [comment]
Yes Extra Files is supposed to be relative to the .atom folder.
